### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by supern64** [Zysen/node-winprocess#2]
I tried to build winprocess and got this error:

```
D:\NET64\drpcclientmod\net64plus>npm install

> winprocess@0.0.2 install D:\NET64\drpcclientmod\net64plus\node_modules\winprocess
> node-gyp rebuild


D:\NET64\drpcclientmod\net64plus\node_modules\winprocess>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  LoadLibraryR.c
  GetProcAddressR.c
..\GetProcAddressR.c(70): warning C4311: 'type cast': pointer truncation from 'LPCSTR' to 'DWORD' [D:\NET64\drpcclientm
od\net64plus\node_modules\winprocess\build\winprocess.vcxproj]
..\GetProcAddressR.c(75): warning C4311: 'type cast': pointer truncation from 'LPCSTR' to 'DWORD' [D:\NET64\drpcclientm
od\net64plus\node_modules\winprocess\build\winprocess.vcxproj]
..\LoadLibraryR.c(222): warning C4311: 'type cast': pointer truncation from 'void *' to 'DWORD' [D:\NET64\drpcclientmod
\net64plus\node_modules\winprocess\build\winprocess.vcxproj]
  winprocess.cc
  win_delay_load_hook.cc
..\winprocess.cc(68): warning C4311: 'type cast': pointer truncation from 'HMODULE' to 'DWORD' [D:\NET64\drpcclientmod\
net64plus\node_modules\winprocess\build\winprocess.vcxproj]
..\winprocess.cc(68): warning C4302: 'type cast': truncation from 'HMODULE' to 'DWORD' [D:\NET64\drpcclientmod\net64plu
s\node_modules\winprocess\build\winprocess.vcxproj]
..\winprocess.cc(191): error C2661: 'v8::Function::NewInstance': no overloaded function takes 2 arguments [D:\NET64\drp
cclientmod\net64plus\node_modules\winprocess\build\winprocess.vcxproj]
..\winprocess.cc(182): warning C4996: 'v8::Value::NumberValue': was declared deprecated [D:\NET64\drpcclientmod\net64pl
us\node_modules\winprocess\build\winprocess.vcxproj]
  c:\users\asus\.node-gyp\10.15.0\include\node\v8.h(2475): note: see declaration of 'v8::Value::NumberValue'
..\winprocess.cc(230): warning C4996: 'v8::Value::IntegerValue': was declared deprecated [D:\NET64\drpcclientmod\net64p
lus\node_modules\winprocess\build\winprocess.vcxproj]
  c:\users\asus\.node-gyp\10.15.0\include\node\v8.h(2476): note: see declaration of 'v8::Value::IntegerValue'
..\winprocess.cc(233): warning C4996: 'v8::Value::IntegerValue': was declared deprecated [D:\NET64\drpcclientmod\net64p
lus\node_modules\winprocess\build\winprocess.vcxproj]
  c:\users\asus\.node-gyp\10.15.0\include\node\v8.h(2476): note: see declaration of 'v8::Value::IntegerValue'
..\winprocess.cc(257): warning C4312: 'type cast': conversion from 'unsigned long' to 'void *' of greater size [D:\NET6
4\drpcclientmod\net64plus\node_modules\winprocess\build\winprocess.vcxproj]
..\winprocess.cc(263): warning C4312: 'type cast': conversion from 'unsigned long' to 'void *' of greater size [D:\NET6
4\drpcclientmod\net64plus\node_modules\winprocess\build\winprocess.vcxproj]
..\winprocess.cc(254): warning C4996: 'v8::Value::IntegerValue': was declared deprecated [D:\NET64\drpcclientmod\net64p
lus\node_modules\winprocess\build\winprocess.vcxproj]
  c:\users\asus\.node-gyp\10.15.0\include\node\v8.h(2476): note: see declaration of 'v8::Value::IntegerValue'
..\winprocess.cc(262): warning C4996: 'v8::Value::IntegerValue': was declared deprecated [D:\NET64\drpcclientmod\net64p
lus\node_modules\winprocess\build\winprocess.vcxproj]
  c:\users\asus\.node-gyp\10.15.0\include\node\v8.h(2476): note: see declaration of 'v8::Value::IntegerValue'
..\winprocess.cc(280): warning C4996: 'v8::Value::IntegerValue': was declared deprecated [D:\NET64\drpcclientmod\net64p
lus\node_modules\winprocess\build\winprocess.vcxproj]
  c:\users\asus\.node-gyp\10.15.0\include\node\v8.h(2476): note: see declaration of 'v8::Value::IntegerValue'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\NET64\drpcclientmod\net64plus\node_modules\winprocess
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN discord-rpc@3.0.1 requires a peer of register-scheme@github:devsnek/node-register-scheme but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! winprocess@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the winprocess@0.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Roaming\npm-cache\_logs\2018-12-31T06_22_09_680Z-debug.log
```
Here is the version information:
```
Node.js : 10.15.0
OS: Windows 10 Home
MSBuild: 14.0.25420.1
Python: 2.7.14
```

**Comment by supern64** [comment]
(Note: look at the edit too)

**Comment by TaxMachine** [comment]
i got the same error and i still can't find out why tf is it doing that

**Comment by supern64** [comment]
> i got the same error and i still can't find out why tf is it doing that

I'd say incompatible Node versions :P
This only works up to Node 8 which is extremely outdated circa 2022, I wonder if I could make it work somehow...
